# Generated by Django 3.1.2 on 2020-11-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='created_user',
            name='phone',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
