# Generated by Django 3.1.2 on 2020-11-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_created_user_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='created_user',
            new_name='userarea',
        ),
    ]
