# Generated by Django 3.1.2 on 2020-11-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201106_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarea',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
