# Generated by Django 3.1.2 on 2020-11-20 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20201116_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('profession', models.CharField(max_length=50)),
                ('experiance', models.CharField(max_length=50)),
                ('engllish_level', models.CharField(choices=[('Excelent', 'Excelent'), ('MEDIUM', 'MEDIUM'), ('Managable', 'Managable')], max_length=10)),
                ('bio', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
