# Generated by Django 3.1.2 on 2020-11-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userarea_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='userarea',
            old_name='user',
            new_name='author',
        ),
    ]
