# Generated by Django 3.1.2 on 2020-11-22 17:28

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='PhoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default=builtins.input),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experiance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
