# Generated by Django 3.1.2 on 2020-11-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201107_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='author',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='userarea',
            name='author',
        ),
    ]
