# Generated by Django 3.1.2 on 2020-11-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userarea_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userarea',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='userarea',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userarea',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userarea',
            name='username',
        ),
    ]
