# Generated by Django 3.1.2 on 2020-11-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201123_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experiance',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
