# Generated by Django 3.1.2 on 2020-11-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201111_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-published_on']},
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='published_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
